POST http://localhost:3000/envios
Content-Type: application/json

{
    "destino": "MDZ",
    "email": "cliente@gmail.com"
}


###
GET http://localhost:3000/envios/pendientes


###
PUT http://localhost:3000/envios/usidfu89s/entregado
